### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by vvcatstar** [concept-graphs/concept-graphs#19]
Now, I am run with the scannet and scannet++ dataset. I run the code with scannet is ok, but when I run the conceptgraph/scripts/run_slam_rgb.py with scannet++ to reconstruction scene, error.
1. first run the generate_gsa_results.py with class_se=ram, and the ram result
![frame_000000](https://github.com/concept-graphs/concept-graphs/assets/45086758/ed13d239-9138-4558-9ff3-5a1b874583eb)
2. run run_slam_rgb.py to run slam and error.
Image size is 1920 * 1440
The error log:
```
python conceptgraph/scripts/run_slam_rgb.py
  0%|                                                            | 0/1172 [00:00<?, ?it/s]/home/zyw/anaconda3/envs/conceptgraph/lib/python3.10/site-packages/imageio/plugins/pillow.py:297: UserWarning: Loading 16-bit (uint16) PNG as int32 due to limitations in pillow's PNG decoder. This will be fixed in a future version of pillow which will make this warning dissapear.
  warnings.warn(
/home/zyw/anaconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  1%|▋                                                  | 16/1172 [00:03<03:43,  5.18it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.3845484256744385 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  1%|▋                                                  | 17/1172 [00:03<03:52,  4.96it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.4994102716445923 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|▊                                                  | 18/1172 [00:03<04:00,  4.79it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.5189590454101562 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|▊                                                  | 19/1172 [00:03<04:12,  4.57it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.5160576105117798 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|▊                                                  | 20/1172 [00:03<04:20,  4.42it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.5655090808868408 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|▉                                                  | 21/1172 [00:04<04:36,  4.16it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.4959553480148315 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|▉                                                  | 22/1172 [00:04<04:45,  4.03it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.4717077016830444 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|█                                                  | 23/1172 [00:04<05:00,  3.82it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.459686517715454 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|█                                                  | 24/1172 [00:05<05:15,  3.64it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.440646767616272 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|█                                                  | 25/1172 [00:05<05:33,  3.44it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.3939265012741089 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|█▏                                                 | 26/1172 [00:05<05:45,  3.31it/s]/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py:188: RuntimeWarning: Max of dot product was 1.3882741928100586 > 1. Inputs were not normalized along dim (-1). Was this intentional?
  warnings.warn(
  2%|█▏                                                 | 27/1172 [00:06<06:04,  3.15it/s]/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [10,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [11,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [12,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [13,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1699449181202/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [68262,0,0], thread: [14,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
  2%|█▏                                                 | 27/1172 [00:06<04:31,  4.22it/s]
Traceback (most recent call last):
  File "/home/zyw/data/repo_common/concept-graphs/conceptgraph/scripts/run_slam_rgb.py", line 133, in <module>
    main(args)
  File "/home/zyw/data/repo_common/concept-graphs/conceptgraph/scripts/run_slam_rgb.py", line 108, in main
    pointclouds, _ = slam.step(pointclouds, frame_cur, frame_prev)
  File "/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/icpslam.py", line 180, in step
    pointclouds = self._map(pointclouds, live_frame, inplace)
  File "/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/pointfusion.py", line 115, in _map
    return update_map_fusion(
  File "/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py", line 899, in update_map_fusion
    pc2im_bnhw = find_correspondences(pointclouds, rgbdimages, dist_th, dot_th)
  File "/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py", line 573, in find_correspondences
    pc2im_bnhw, _ = find_similar_map_points(
  File "/home/zyw/data/repo_common/concept-graphs/gradslam/gradslam/slam/fusionutils.py", line 388, in find_similar_map_points
    frame_points[pc2im_bnhw[:, 0], pc2im_bnhw[:, 1]] = vertex_maps[
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by georgegu1997** [comment]
Thanks for your interest in our project!

For message `RuntimeWarning: Max of dot product was 1.3882741928100586 > 1. Inputs were not normalized along dim (-1). Was this intentional?` you saw during running the rgb slam, this probably means there are not enough overlapped points between the new frame and existing point cloud built by the SLAM system. The underlying SLAM algorithm we used is GradSLAM, and it requires consecutive frames to have enough overlapping to work well (the camera should not jump around). So please check whether this is true. 

But also the a possible cause is that the input camera intrinsics or extrinsics are wrong. Could you double check the input poses? One useful trick to debug is to run `run_slam_rgb.py` with `--end 20` and `--visualize` arguments so that it visualize the point cloud after processing 20 frames. From the point cloud, you should be able to see whether the camera parameters are good or not.

**Comment by georgegu1997** [comment]
Closing this issue due to inactivity. Feel free to re-open it if the question persists.
