### ISSUE TITLE
Failed to build chamferdist

### ISSUE THREAD

**Issue by gauraviiita** [concept-graphs/concept-graphs#2]
Hello all, 
Great work, and thank you for providing the source code publically.

I need help with building chamferdist. My system configuration is Ubuntu 22.04, Python = 3.10.13, Pytorch version is 2.1.0+cu121.
NVIDIA Driver version 525.125 and Cuda version 12.0.

The error is as follows. 

Processing /home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/chamferdist
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: chamferdist
  Building wheel for chamferdist (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/chamferdist/setup.py", line 76, in <module>
          setup(
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 525, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (11.7) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chamferdist
  Running setup.py clean for chamferdist
Failed to build chamferdist
ERROR: Could not build wheels for chamferdist, which is required to install pyproject.toml-based projects

**Comment by gauraviiita** [comment]
I am also getting the error when I am running the command. 

python scripts/run_slam_rgb.py \
    --dataset_root /home/gaurav/Desktop/ConceptGraphs/concept-graphs/Datasets/Replica \
    --dataset_config /home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    --scene_id room0 \
    --image_height 480 \
    --image_width 640 \
    --stride 5 \
    --visualize
    
The error is as follows.

[2023-10-08 04:49:34,322] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/scripts/run_slam_rgb.py", line 12, in <module>
    from conceptgraph.dataset.datasets_common import get_dataset
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/dataset/datasets_common.py", line 26, in <module>
    from gradslam.datasets import datautils
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/gradslam/__init__.py", line 8, in <module>
    from . import odometry
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/gradslam/odometry/__init__.py", line 1, in <module>
    from .gradicp import *
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/gradslam/odometry/gradicp.py", line 7, in <module>
    from .icputils import point_to_plane_gradICP
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/gradslam/odometry/icputils.py", line 3, in <module>
    from chamferdist.chamfer import knn_points
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/chamferdist/__init__.py", line 1, in <module>
    from .chamfer import ChamferDistance
  File "/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/chamferdist/chamfer.py", line 12, in <module>
    from chamferdist import _C
ImportError: cannot import name '_C' from partially initialized module 'chamferdist' (most likely due to a circular import) (/home/gaurav/Desktop/ConceptGraphs/concept-graphs/conceptgraph/chamferdist/__init__.py)



Thank you

**Comment by krrish94** [comment]
Hi @gauraviiita,

You should technically be able to run the entire package without needing the `chamferdist` package.

From your error message, I deduce you are trying to build the `main` branch of gradslam and not the `conceptfusion` branch? I just looked up the readme and there seems to be a typo on our end. Could you try running this instead?

```
git clone https://github.com/gradslam/gradslam.git
cd gradslam
git checkout conceptfusion
pip install -e .
```

It'd be great to know if this fix works (if it does, we will update the `README`)

**Comment by gauraviiita** [comment]
Thank you for the quick reply. I am going to follow the instructions you gave and let you know soon.

**Comment by gauraviiita** [comment]
Hello @krrish94 

I followed the instructions given by I installed grandslam in the concept-graphs folder and then successfully checked it to conceptfusion branch. 

After that, I run the command. As given below
python scripts/run_slam_rgb.py \
    --dataset_root /home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica \
    --dataset_config /home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    --scene_id room0 \
    --image_height 480 \
    --image_width 640 \
    --stride 5 \
    --visualize


And I am getting a similar error as earlier. Please let me know the next step to remove this error.
Also, I installed all the models GSAM, grandslam and LLaVa in the concept-graphs folder.

[2023-10-08 00:54:55,284] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/scripts/run_slam_rgb.py", line 13, in <module>
    from dataset.datasets_common import get_dataset
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/datasets_common.py", line 26, in <module>
    from gradslam.datasets import datautils
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/gradslam/__init__.py", line 8, in <module>
    from . import odometry
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/gradslam/odometry/__init__.py", line 1, in <module>
    from .gradicp import *
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/gradslam/odometry/gradicp.py", line 7, in <module>
    from .icputils import point_to_plane_gradICP
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/gradslam/odometry/icputils.py", line 3, in <module>
    from chamferdist.chamfer import knn_points
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/chamferdist/__init__.py", line 1, in <module>
    from .chamfer import ChamferDistance
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/chamferdist/chamfer.py", line 12, in <module>
    from chamferdist import _C
ImportError: /home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/chamferdist/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by georgegu1997** [comment]
Hi @gauraviiita Have you tried building `chamferdist` package again? Did it build successfully?

**Comment by krrish94** [comment]
Also, I would recommend installing `gradslam` in a different directory altogether, to mirror how things are setup on our internal tests

**Comment by georgegu1997** [comment]
I tried the following commands on my machine and it builds successfully. 

```bash
conda create -n cg-test
conda activate cg-test
conda install python=3.10
cd ..
cd chamferdist/
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
pip install .
```

**Comment by gauraviiita** [comment]
@krrish94 

Yes, I installed grandslam in a different directory, and now it is working.

python scripts/run_slam_rgb.py \
    --dataset_root /home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica \
    --dataset_config /home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    --scene_id room0 \
    --image_height 480 \
    --image_width 640 \
    --stride 5 \
    --visualize
    
I have successfully run this command. 

Thank you very much.

**Comment by ndrwmlnk** [comment]
Additionally, while building **chamferdist**,

```
git clone https://github.com/krrish94/chamferdist.git
cd chamferdist
pip install .
```
this error may occur: "_#error C++17 or later compatible compiler is required to use PyTorch._"

It can be solved by updating [line 18](https://github.com/krrish94/chamferdist/blob/38dab67945d8493cff55628254da00c4b2b215db/setup.py#L18) in _chamferdist/setup.py_

```
#extra_compile_args = {"cxx": ["-std=c++14"]}  # old
extra_compile_args = {"cxx": ["-std=c++17"]}  # new
```
Reference: https://github.com/open-mmlab/mmdeploy/issues/2529
