### ISSUE TITLE
Running slam/cfslam_pipeline_batch.py faces "RuntimeError: Unknown layout"

### ISSUE THREAD

**Issue by jtwty** [concept-graphs/concept-graphs#25]
Hello, @georgegu1997 
&nbsp;&nbsp;&nbsp;&nbsp; When i running the script of "slam/cfslam_pipeline_batch.py", I face the error of "RuntimeError: Unknown layout". Maybe some input datas's layout have wrong format, i can't make sure this.
&nbsp;&nbsp;&nbsp;&nbsp;Please tell me how i can fix it, thank you!
       

>(newconceptgraph) cuijin@supermicro72:~/projects/concept-graphs/conceptgraph$ bash run_3D_object_mapping.sh 
Setting image height and width to 680 x 1200
Loaded class colors from  /home/cuijin/projects/data/Replica/room0/gsa_classes_none_colors.json
  0%|▎                                                                                                    | 1/400 [00:01<11:50,  1.78s/it]
Error executing job with overrides: ['dataset_root=/home/cuijin/projects/data/Replica', 'dataset_config=/home/cuijin/projects/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml', 'stride=5', 'scene_id=room0', 'spatial_sim_type=overlap', 'mask_conf_threshold=0.95', 'match_method=sim_sum', 'sim_threshold=1.2', 'dbscan_eps=0.1', 'gsa_variant=none', 'class_agnostic=True', 'skip_bg=True', 'max_bbox_area_ratio=0.5', 'save_suffix=overlap_maskconf0.95_simsum1.2_dbscan.1_merge20_masksub', 'merge_interval=20', 'merge_visual_sim_thresh=0.8', 'merge_text_sim_thresh=0.8', 'save_objects_all_frames=True']
Traceback (most recent call last):
  File "/home/cuijin/projects/concept-graphs/conceptgraph/slam/cfslam_pipeline_batch.py", line 442, in <module>
    main()
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/cuijin/projects/concept-graphs/conceptgraph/slam/cfslam_pipeline_batch.py", line 275, in main
    spatial_sim = compute_spatial_similarities(cfg, fg_detection_list, objects)
  File "/home/cuijin/projects/concept-graphs/conceptgraph/slam/mapping.py", line 39, in compute_spatial_similarities
    spatial_sim = compute_overlap_matrix_2set(cfg, objects, detection_list)
  File "/home/cuijin/projects/concept-graphs/conceptgraph/slam/utils.py", line 293, in compute_overlap_matrix_2set
    iou = compute_3d_iou_accuracte_batch(bbox_map, bbox_new) # (m, n)
  File "/home/cuijin/projects/concept-graphs/conceptgraph/utils/ious.py", line 172, in compute_3d_iou_accuracte_batch
    inter_vol, iou = ops.box3d_overlap(bbox1.float(), bbox2.float())
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/pytorch3d/ops/iou_box3d.py", line 164, in box3d_overlap
    vol, iou = _box3d_overlap.apply(boxes1, boxes2)
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/cuijin/anaconda3/envs/newconceptgraph/lib/python3.10/site-packages/pytorch3d/ops/iou_box3d.py", line 103, in forward
    vol, iou = _C.iou_box3d(boxes1, boxes2)
RuntimeError: Unknown layout

**Comment by alik-git** [comment]
I will take a look at this tomorrow

**Comment by alik-git** [comment]
Hmm I think I have seen this error before but I'm honestly not sure. This thread also points to pytorch and cuda versions. 

https://github.com/Vahe1994/AQLM/issues/20#issuecomment-1979516088

> Hi @sankeerth43 ! I don't think you're doing anything wrong. We're honestly not sure where this problem originates from. We don't have access to any Nvidia L4 GPUs to try and reproduce the error either. One thing you could do is delete the torch compiled kernels cache (usually ~/.cache/torch_extensions), update the aqlm library (pip install --upgrade aqlm) and maybe check that the compiler for CUDA compilation is sourced correctly which nvcc. Other than that, I'm not sure. We're trying to identify the error as well.
> 
> thanks!
> turns out it's an issue with the newest pytorch 2.2.1. Capping pytorch==2.1.0 solved this for me.

I would suggest just trying an [older pytorch version](https://pytorch.org/get-started/previous-versions/#linux-and-windows-8) that is compatible with cuda11.7, say 

```bash
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
```

Ultimately, you will have to experiment with finding the right set of packages that work on your machine.

**Comment by jtwty** [comment]
Hi, @alik-git 
&nbsp;&nbsp;&nbsp;&nbsp;In function "concept-graphs/conceptgraph/utils/ious.py",  I change the data of bbox1 and bbox2
>bbox1 = bbox1[:, [0, 2, 5, 3, 1, 7, 4, 6],:]
    bbox2 = bbox2[:, [0, 2, 5, 3, 1, 7, 4, 6],:]
    a=torch.ones_like(bbox1)
    b=torch.ones_like(bbox2)

&nbsp;&nbsp;&nbsp;&nbsp;After this operation, the function can run without error, so i think that the bbox1 and bbox2  generate wrong data, but i don't know the right format about them
&nbsp;&nbsp;&nbsp;&nbsp;I will try to change the pytorch version firstly

**Comment by georgegu1997** [comment]
This error might be due to the underlying data layout of bbox1 and bbox2, specifically whether it's contiguous/sliced/indexed. Can you try making a copy of the input tensors (by `.clone()`) or make them contiguous (by `.contiguous()`) before the following line? Also double check what those tensors look like by checking their shape, dtype, range, flags, and NaN if any. 

```
inter_vol, iou = ops.box3d_overlap(bbox1.float(), bbox2.float())
```

**Comment by jtwty** [comment]
&nbsp;&nbsp;&nbsp;&nbsp; I change the pytorch version from '2.2.0' to '2.0.1', and the pytorch3d version is '0.7.5'; After that, my code could run without error. Thanks for your help!

**Comment by alik-git** [comment]
awesome! happy to help
