### ISSUE TITLE
Questions for running slam/r3d_stream_rerun_realtime_mapping.py

### ISSUE THREAD

**Issue by percypeng5221** [concept-graphs/concept-graphs#74]
Hi, I have troubles running the slam/r3d_stream_rerun_realtime_mapping.py file. I'm using the code from ali-dev branch and I've modified the DemoApp structure so the input depth and rgb images are obtained from a D435i intel realsense camera. This part is working fine cause I can get segmented images saved in my computer. But I'm looking at the code structure and I noticed that the function for generating annotated images are executed after making captions.
```
[2024-10-14 16:42:06,914][WARNING][m:optional_rerun_wrapper][fn:orr_log_vlm_image][ln:132] - VLM image not found at path: /home/percy/princeton/data/record3d/convenience_store_record3d_dataset_preprocessed/exps/s_detections_stride13/vis/0annotated_for_vlm.jpg\n
[2024-10-14 16:42:06,914][WARNING][m:optional_rerun_wrapper][fn:orr_log_vlm_image][ln:132] - VLM image not found at path: /home/percy/princeton/data/record3d/convenience_store_record3d_dataset_preprocessed/exps/s_detections_stride13/vis/0annotated_for_vlm_w_edges.jpg
```
And this would make the captions None and cause bugs like this: 
```
Traceback (most recent call last):
  File "/home/percy/princeton/concept-graphs/conceptgraph/slam/r3d_stream_rerun_realtime_mapping.py", line 354, in main
    filtered_gobs = filter_gobs(resized_gobs, image_rgb,
  File "/home/percy/princeton/concept-graphs/conceptgraph/slam/utils.py", line 894, in filter_gobs
    filtered_captions = filter_captions(gobs['captions'], gobs['detection_class_labels'])
  File "/home/percy/princeton/concept-graphs/conceptgraph/slam/utils.py", line 802, in filter_captions
    captions_index = {item['id']: index for index, item in enumerate(captions)}
TypeError: 'NoneType' object is not iterable
```
Then how did this code get to work in the first place with realtime scene graph construction?
This is my rerun_realtime_mapping.yaml file:
```
defaults:
  - base
  - base_mapping
  # - replica
  - record3d
  - sam
  - classes
  - logging_level
  - _self_


detections_exp_suffix: s_detections_stride13 # helpful label to identify your detections
force_detection: !!bool True
save_detections: !!bool True

make_edges: !!bool False

stride: 10
exp_suffix: r_mapping_stride13 # helpful label to identify your mapping experiment

save_video: !!bool False
save_objects_all_frames: !!bool False

downsample_voxel_size: 0.01
obj_pcd_max_points: 5000

debug_render: !!bool False
vis_render: !!bool False

denoise_interval: 5           # Run DBSCAN every k frame. This operation is heavy
filter_interval: 5            # Filter objects that have too few associations or are too small
merge_interval: 5             # Merge objects based on geometric and semantic similarity
run_denoise_final_frame: !!bool True
run_filter_final_frame: !!bool True
run_merge_final_frame: !!bool True

dbscan_remove_noise: !!bool True
dbscan_eps: 0.1
dbscan_min_points: 10

# Selection criteria of the fused object point cloud
obj_min_points: 0
obj_min_detections: 1

# For merge_overlap_objects() function
use_rerun: !!bool True
save_rerun: !!bool True

# hydra:
#   verbose: true
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     downsample_voxel_size: 0.025, 0.01, 0.001, 0.001
  #     obj_pcd_max_points: 5000, 10000, 100000, 100000
```
Please give me a hand!
Thanks!

**Comment by arunmadhusud** [comment]
@percypeng5221 Hi, Were you able to find a solution? I'm currently running into the same problem and would appreciate any insights you might have. Thanks!

**Comment by percypeng5221** [comment]
Sorry, I didn't find a solutions. @arunmadhusud

**Comment by asandstar** [comment]
My solution is to initialize with an empty list.
